name: Deploy to Firebase Hosting on PR merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Change to project directory
      run: cd web-pan-main

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EL_BUEN_SABOR_ONLINE }}
      run: |
        npx firebase-tools deploy --only hosting --token $FIREBASE_SERVICE_ACCOUNT